#coding=utf-8
#----------------------
#进程间通信
#我们以Queue为例，在父进程中创建两个子进程，一个往Queue里写数据，一个从Queue里读数据：
#一个proecess往queue里面put一个,马上就被另一个process给read出来,表明多进程是同时进行的.

from multiprocessing import Process, Queue
import os, time, random

# 写数据进程执行的代码:
def write(q):
    for value in ['A', 'B', 'C']:
        print 'write Put %s to queue...' % value
        "往queue里面写数据"
        q.put(value)
        wr = q.get(True)
        print 'write Get %s to queue...' %wr
        time.sleep(random.random())

# 读数据进程执行的代码:
def read(q):
    while True:
        "从queue里面取数据"
        value = q.get(True)
        print 'read Get %s from queue.' % value
        print 'read Put 123 to queue...' 
        q.put(123)

if __name__=='__main__':
    # 父进程创建Queue，并传给各个子进程：
    q = Queue()
    pr = Process(target=read, args=(q,))
    pw = Process(target=write, args=(q,))
    # 启动子进程pr，读取:
    pr.start()
    # 启动子进程pw，写入:
    pw.start()
    print ('q -->%s'%q)
    # 等待pw结束:
    pw.join()
    # pr进程里是死循环，无法等待其结束，只能强行终止:
    pr.terminate()
'''
子进程里面同时有get和put,是很难控制的.

q --><multiprocessing.queues.Queue object at 0x000000000237F5F8>
write Put A to queue...
read Get A from queue.
read Put 123 to queue...
write Get 123 to queue...
write Put B to queue...
read Get B from queue.
read Put 123 to queue...
write Get 123 to queue...
write Put C to queue...
read Get C from queue.
read Put 123 to queue...
write Get 123 to queue...
Hit any key to close this window...
'''
'''
C:\windows\system32\cmd.exe /c (python process_communicate.py)
q --><multiprocessing.queues.Queue object at 0x000000000250D5F8>
write Put A to queue...
write Get A to queue...
write Put B to queue...
read Get B from queue.
read Put 123 to queue...
write Get 123 to queue...
write Put C to queue...
read Get C from queue.
read Put 123 to queue...
write Get 123 to queue...
Hit any key to close this window...
'''
'''
C:\windows\system32\cmd.exe /c (python process_communicate.py)
q --><multiprocessing.queues.Queue object at 0x00000000024A6630>
Put A to queue...
write Get A to queue...
Put B to queue...
read Get B from queue.
read Put 123 to queue...
write Get 123 to queue...
Put C to queue...
read Get C from queue.
read Put 123 to queue...
write Get 123 to queue...
Hit any key to close this window...
'''
'''

C:\windows\system32\cmd.exe /c (python process_communicate.py)
q --><multiprocessing.queues.Queue object at 0x00000000024C75F8>
Put A to queue...
Put B to queue...
Get B from queue.
Put C to queue...
Get C from queue.
Hit any key to close this window...
'''
'''
Put A to queue...
Get A from queue.
Put B to queue...
Get B from queue.
Put C to queue...
Get C from queue.
Hit any key to close this window...

'''
